// <auto-generated />
namespace HotOrNot.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addtitledesc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addtitledesc));
        
        string IMigrationMetadata.Id
        {
            get { return "201809161414461_Add-titledesc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
